# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d0becc57b93bf0af346a9f1b3f49845a"
name = "wishlist-firstapp"
handle = "wishlist-firstapp"
application_url = "https://arm-sellers-deck-li.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "aryan-app-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://arm-sellers-deck-li.trycloudflare.com/auth/callback",
  "https://arm-sellers-deck-li.trycloudflare.com/auth/shopify/callback",
  "https://arm-sellers-deck-li.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
